apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webapplication1-back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapplication1-back
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: webapplication1-back
        image: redis
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: webapplication1-back
spec:
  ports:
  - port: 6379
  selector:
    app: webapplication1-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication1
  namespace: default
  labels:
    app: webapplication1
spec:
  replicas: 1
  selector:
    matchLabels:
        app: webapplication1
  template:
    metadata:
      name: webapplication1
      labels:
        app: webapplication1
    spec:
      containers:
      - name: webapplication1
        image: daisukenishinoacr.azurecr.io/webapplication1:<Tag>
        resources: 
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: webapplication1
  labels:
    app: webapplication1
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: webapplication1